// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/meta_fetcher/interface.go

package meta_fetcher

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetaFetcher is a mock of IMetaFetcher interface.
type MockMetaFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockMetaFetcherMockRecorder
}

// MockMetaFetcherMockRecorder is the mock recorder for MockMetaFetcher.
type MockMetaFetcherMockRecorder struct {
	mock *MockMetaFetcher
}

// NewMockMetaFetcher creates a new mock instance.
func NewMockMetaFetcher(ctrl *gomock.Controller) *MockMetaFetcher {
	mock := &MockMetaFetcher{ctrl: ctrl}
	mock.recorder = &MockMetaFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaFetcher) EXPECT() *MockMetaFetcherMockRecorder {
	return m.recorder
}

// NumberOfAccounts mocks base method.
func (m *MockMetaFetcher) NumberOfAccounts() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberOfAccounts")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberOfAccounts indicates an expected call of NumberOfAccounts.
func (mr *MockMetaFetcherMockRecorder) NumberOfAccounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfAccounts", reflect.TypeOf((*MockMetaFetcher)(nil).NumberOfAccounts))
}
