// Code generated by MockGen. DO NOT EDIT.
// Source: rpc.go

package rpc

import (
	types "ftm-explorer/internal/types"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "github.com/golang/mock/gomock"
)

// MockRpc is a mock of Rpc interface.
type MockRpc struct {
	ctrl     *gomock.Controller
	recorder *MockRpcMockRecorder
}

// MockRpcMockRecorder is the mock recorder for MockRpc.
type MockRpcMockRecorder struct {
	mock *MockRpc
}

// NewMockRpc creates a new mock instance.
func NewMockRpc(ctrl *gomock.Controller) *MockRpc {
	mock := &MockRpc{ctrl: ctrl}
	mock.recorder = &MockRpcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRpc) EXPECT() *MockRpcMockRecorder {
	return m.recorder
}

// BlockByNumber mocks base method.
func (m *MockRpc) BlockByNumber(arg0 uint64) (*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByNumber", arg0)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByNumber indicates an expected call of BlockByNumber.
func (mr *MockRpcMockRecorder) BlockByNumber(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByNumber", reflect.TypeOf((*MockRpc)(nil).BlockByNumber), arg0)
}

// TransactionByHash mocks base method.
func (m *MockRpc) TransactionByHash(arg0 common.Hash) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionByHash", arg0)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionByHash indicates an expected call of TransactionByHash.
func (mr *MockRpcMockRecorder) TransactionByHash(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionByHash", reflect.TypeOf((*MockRpc)(nil).TransactionByHash), arg0)
}
