package auth

import (
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

// Test that signature verification works
func TestVerification_VerifySignature(t *testing.T) {
	message := "I am signing my one-time nonce: ABCDEF"
	address := common.HexToAddress("0x83A6524Be9213B1Ce36bCc0DCEfb5eb51D87aD10")
	// signature generated by Metamask using web3.eth.personal.sign(message, accounts[0], '')
	signature, _ := hexutil.Decode("0xac70a4396976772a556900fea540033736380ddddb591a3bc5bee30321f5bbdb060969d6e45e03a58f2138f39705a4d6572f1856e902be421bed847cb53f371f1c")

	result, err := VerifySignature(message, address, signature)
	if err != nil {
		t.Fatal(err)
	}
	if !result {
		t.Fatal("signature verification failed")
	}
}
